spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://101.200.186.89:3306/myblog?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: zjwhayafd123

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect

logging:
  level:
    root: warn
    com.zjw: info
  file:
    name: blog-pro.log
    path: /log

server:
  port: 8081
